server:
    port: 8080
    servlet:
        context-path: /api
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/chengdacommunity?useSSL=false&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
    # 支持uri匹配策略
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    redis:
        port: 6379
        host: localhost
        database: 4
# 连接池
# myBatisPlus
mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    global-config:
        db-config:
            logic-delete-field: isDelete
            logic-delete-value: 1
            logic-not-delete-value: 0
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl